name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    uses: spuxx1701/ci-cd/.github/workflows/npm_lint.yml@v4.1.0

  test:
    uses: spuxx1701/ci-cd/.github/workflows/npm_test-playwright.yml@v4.1.0
